### ISSUE TITLE
Question about creating wig files for data_processing.py

### ISSUE THREAD

**Issue by DaehwaYoun** [lingxusb/Riboformer#2]
I am trying to run Riboformer, but I am having trouble creating required wig files.
So, I want to ask whether there is any recommended tool for creating fixed step wig files for data_processing.py from BAM files.

**Comment by lingxusb** [comment]
> I am trying to run Riboformer, but I am having trouble creating required wig files. So, I want to ask whether there is any recommended tool for creating fixed step wig files for data_processing.py from BAM files.

Thank you for your question. I think you can go with any published tool that you are comfortable with. For bacteria, I would recommend the Buskirk Group's codes: [github](https://github.com/greenlabjhmi/2018_Bacterial_Pipeline_riboseq), original publication is [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7079819/ )

I heard other people has used [DeepTools](https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html ). The Lareau lab and the Wallace lab have developed riboviz and the publication is [here](https://academic.oup.com/bioinformatics/article/38/8/2358/6528320?login=false)

I hope these information helps. Please let me know if there is any further question.

**Comment by nayanvs** [comment]
I have generating wig files with same header for marmoset data (or human) as mentioned in the demo data for Yeast. Specific step by step commands are mentioned below.

1. I used the standard command from samtools to generate forward and reverse bam files, as mentioned below:
samtools view -b -F 16 or samtools view -b -f 16

2. Sorted and indexed them using the commands:
samtools sort
samtool index

3. Converted bam files to wig format using 
bam2wig.py
(https://github.com/guifengwei/glib/blob/master/bam2wig.py)

This throws an **UnboundLocalError: local variable 'read' referenced before assignment**

I believe wig files are required to be prepared using specific wig tool. And also possibly forward and reverse strand specific files.

@lingxusb I would greatly appreciate it if you could elaborate the exact code/command to create bam files and wig files.
